config/routes.rb
Rails.application.routes.draw do


  scope "(:locale)", :locale => /en|ru|az/ do
      mount RailsAdmin::Engine => '/admpanel', as: 'rails_admin'

      resources :locales
  resources :pages
  resources :pagenames
  resources :partners
  resources :works
  	  resources :abouts
      resources :contact
      resources :career

  resources :services
  root to: 'site#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
	  mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/locale.rb
class Locale < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
	belongs_to :pagename
end

app/models/pagename.rb
class Pagename < ApplicationRecord
	has_many :pages
end

app/models/partner.rb
class Partner < ApplicationRecord
	  mount_uploader :logo, ImageUploader

end

app/models/service.rb
class Service < ApplicationRecord
		  mount_uploader :image, ImageUploader

end

app/models/work.rb
class Work < ApplicationRecord
		  mount_uploader :image, ImageUploader

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
     @pages = Page.where(pagename_id:params[:id],locale_code:I18n.locale).first 
         
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :desc, :text, :pagename_id, :locale_code)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.where(locale:I18n.locale).all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :desc, :text, :image, :main, :locale)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	
  	@works = Work.where(locale:I18n.locale).all
  	@services = Service.where(locale:I18n.locale,main:"1.0").all
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :desc, :text, :image, :locale)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/career_helper.rb
module CareerHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/pagenames_helper.rb
module PagenamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/services/_form.html.erb
<%= form_for(service) do |f| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :main %>
    <%= f.text_field :main %>
  </div>

  <div class="field">
    <%= f.label :locale %>
    <%= f.text_field :locale %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
    <div class="container-fluid no-padding pagebanner" style="background-image: url(http://lolthemes.com/demo/wpm/manufactory/wp-content/themes/manufactory/images/page-banner.jpg);">
    <div class="page-banner-inner">
      <div class="container">
        <h3>
          Xidmetler        </h3>
      </div>
    </div>
  </div>
  
  <div class="container-fluid no-padding page-breadcrumb">
    <div class="container">
                <div class="breadcrumb">
            <!-- Breadcrumb NavXT 5.5.2 -->
<span property="itemListElement" typeof="ListItem"><a property="item" typeof="WebPage" title="Go to Manufactory." href="/" class="home"><span property="name">Ana sehife</span></a><meta property="position" content="1"></span> &gt; <span property="itemListElement" typeof="ListItem"><span property="name">Xidmetler</span><meta property="position" content="2"></span>          </div>
              </div>
  </div>
  
<main id="main" class="site-main no-padding no-margin">
  <div class="page-content">    
    <div class="container">
      <div class="row">
        <div class="content-area full-content col-md-12 no-padding">
          <div id="post-45" class="post-45 page type-page status-publish hentry">
    <div class="entry-content">
    <div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"> 
  <div class="container weare-section">
        <div class="row">
                
          <% @services.each do |service| %>
                    <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="weare-box">
              <img src="<%= service.image %>" class="attachment-manufactory-370-306 size-manufactory-370-306 wp-post-image" alt="service-detail-2" width="360" height="306">             <div class="weare-content">
                <h3><a href="/services/<%= service.id %>"><%= service.name %></a></h3>
                
                <p><%= service.desc %></p>
              </div>
            </div>
          </div>
                   <% end %>
            
    </div>
  </div>
  </div></div></div></div>
      </div>
</div>        </div>
              </div>
    </div>
  </div>
</main>

    

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
    <div class="container-fluid no-padding pagebanner" style="background-image: url(<%= @service.image %>);">
    <div class="page-banner-inner">
      <div class="container">
        <h3>
          <%= @service.name %>        </h3>
      </div>
    </div>
  </div>
  
  <div class="container-fluid no-padding page-breadcrumb">
    <div class="container">
             <div class="breadcrumb">
            <!-- Breadcrumb NavXT 5.5.2 -->
<span property="itemListElement" typeof="ListItem"><a property="item" typeof="WebPage" title="Go to Manufactory." href="/" class="home"><span property="name">Ana sehife</span></a><meta property="position" content="1"></span> &gt; <span property="itemListElement" typeof="ListItem"><a property="item" typeof="WebPage" title="Go to Service." href="/services" class="post post-manufactor_service-archive"><span property="name">Xidmetler</span></a><meta property="position" content="2"></span> &gt; <span property="itemListElement" typeof="ListItem"><span property="name"><%= @service.name %></span><meta property="position" content="3"></span>          </div>
              </div>
  </div>
  
<main id="main" class="site-main no-padding no-margin">
  <div class="page-content">    
    <div class="container">
      <div class="row">
        <div class="content-area full-content col-md-12 no-padding">
          <div id="post-45" class="post-45 page type-page status-publish hentry">
    <div class="entry-content">
    <div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper"> 
  <div class="container weare-section">
        <div class="row">
       
         
                    <div class="col-md-12 col-sm-12 col-xs-12">
                    
                    <div class="section-header">
                    <h3><%= @service.name %> </h3>                 </div>
              <p><%= @service.text %></p>      
          </div>
           
            
    </div>
  </div>
  </div></div></div></div>
      </div>
</div>        </div>
              </div>
    </div>
  </div>
</main>

    