config/routes.rb
Rails.application.routes.draw do


  scope "(:locale)", :locale => /en|ru|az/ do
      mount RailsAdmin::Engine => '/admpanel', as: 'rails_admin'

      resources :locales
  resources :pages
  resources :pagenames
  resources :partners
  resources :works
  	  resources :abouts
      resources :contact
      resources :career

  resources :services
  root to: 'site#index'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
	  mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/locale.rb
class Locale < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
	belongs_to :pagename
end

app/models/pagename.rb
class Pagename < ApplicationRecord
	has_many :pages
end

app/models/partner.rb
class Partner < ApplicationRecord
	  mount_uploader :logo, ImageUploader

end

app/models/service.rb
class Service < ApplicationRecord
		  mount_uploader :image, ImageUploader

end

app/models/work.rb
class Work < ApplicationRecord
		  mount_uploader :image, ImageUploader

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:name, :desc, :text, :categ, :locale)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
     @pages = Page.where(pagename_id:params[:id],locale_code:I18n.locale).first 
         
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:name, :desc, :text, :pagename_id, :locale_code)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	
  	@works = Work.where(locale:I18n.locale).all
  	@services = Service.where(locale:I18n.locale,main:"1.0").all
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :desc, :text, :image, :locale)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/career_helper.rb
module CareerHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/pagenames_helper.rb
module PagenamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/abouts/_form.html.erb
<%= form_for(about) do |f| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :categ %>
    <%= f.number_field :categ %>
  </div>

  <div class="field">
    <%= f.label :locale %>
    <%= f.text_field :locale %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
    <div class="container-fluid no-padding pagebanner" style="background-image: url(http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/pagebanner-about.jpg);">
    <div class="page-banner-inner">
      <div class="container">
        <h3>
          Haqqımızda      </h3>
      </div>
    </div>
  </div>
  
  <div class="container-fluid no-padding page-breadcrumb">
    <div class="container">
                <div class="breadcrumb">
            <!-- Breadcrumb NavXT 5.5.2 -->
<span property="itemListElement" typeof="ListItem"><a property="item" typeof="WebPage" title="Go to Manufactory." href="/" class="home"><span property="name">Ana səyhifə</span></a><meta property="position" content="1"></span> &gt; <span property="itemListElement" typeof="ListItem"><span property="name">  Haqqımızda</span><meta property="position" content="2"></span>          </div>
              </div>
  </div>
  
<main id="main" class="site-main no-padding no-margin">
  <div class="page-content">    
    <div class="container">
      <div class="row">
        <div class="content-area full-content col-md-12 no-padding">
          <div id="post-8" class="post-8 page type-page status-publish hentry">
    <div class="entry-content">
    <div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper">
  
    <div class="container aboutus-section ">
      <div class="row">
        <div class="col-md-6 aboutus-image">
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-6">
              <img src="http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/aboutus-1-285x373.jpg" class="attachment-manufactory-285-373 size-manufactory-285-373" alt="aboutus-1" srcset="http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/aboutus-1-285x373.jpg 285w, http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/aboutus-1-229x300.jpg 229w, http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/aboutus-1.jpg 290w" sizes="(max-width: 285px) 100vw, 285px" width="285" height="373">
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
              <img src="http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/aboutus-2.jpg" class="attachment- manufactory-285-373 size- manufactory-285-373" alt="aboutus-2" srcset="http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/aboutus-2.jpg 290w, http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/aboutus-2-229x300.jpg 229w, http://lolthemes.com/demo/wpm/manufactory/wp-content/uploads/2016/07/aboutus-2-285x373.jpg 285w" sizes="(max-width: 290px) 100vw, 290px" width="290" height="380">
            </div>
          </div>
        </div>
        <div class="col-md-6 aboutus-content">
          <p> It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
          
        </div>
      </div>
    </div>  
  
    
  
  
  </div></div></div></div>
      </div>
</div>        </div>
              </div>
    </div>
  </div>
</main>

     

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @about.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @about.desc %>
</p>

<p>
  <strong>Text:</strong>
  <%= @about.text %>
</p>

<p>
  <strong>Categ:</strong>
  <%= @about.categ %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @about.locale %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>

app/views/works/_form.html.erb
<%= form_for(@work, :html => { :multipart => true }) do |f| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :locale %>
    <%= f.text_field :locale %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Text</th>
      <th>Image</th>
      <th>Locale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.name %></td>
        <td><%= work.desc %></td>
        <td><%= work.text %></td>
        <td><%= work.image %></td>
        <td><%= work.locale %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @work.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @work.desc %>
</p>

<p>
  <strong>Text:</strong>
  <%= @work.text %>
</p>

<p>
  <strong>Image:</strong>
  <%= @work.image %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @work.locale %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>